# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Amzy Amalia Zarcu | Game Programming Portfolio
# Description of the Site
description: 
# URL of Image of the Site
site-image: ../assets/images/giornodots.png
# Keywords of the Site
site-keywords: Portfolio, Game, Programming, Amzy, Amalia, Zarcu
# URL for the Image of custom Favicon
favicon-url: ../assets/images/giornodots.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: ../images/IntakeCyberpunkScreenshot.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: amalia.zarcu@gmail.com
facebook_username: /
twitter_username: /
instagram_username: /
linkedin_username: Amalia (Amzy) Zarcu
github_username:  amzy55
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: /

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Amzy Amalia Zarcu
# URL for the Image of the Author
author-image: ../assets/images/MeZoom.png
# 60 Words About the Author
author-about: Info about me to add Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.linkedin.com/in/amalia-amzy-zarcu-001b57295/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
